# https://taskfile.dev
version: '3'

tasks:
  build:
    deps:
      - build:container
    cmds:
      - docker run --rm -v "{{.TASKFILE_DIR}}/src":/src -w /src digital-circuit-verilog iverilog {{.CLI_ARGS}}
      - docker run --rm -v "{{.TASKFILE_DIR}}/src":/src -w /src digital-circuit-verilog vvp a.out
    silent: true

  build:container:
    ENV:
      DOCKER_BUILDKIT: 0
    cmds:
      - docker build -f .devcontainer/Containerfile -t digital-circuit-verilog .
    status:
      - docker image inspect digital-circuit-verilog
    silent: true
