# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

USER root
RUN apt-get update
RUN apt-get install -y which

# Install Homebrew
RUN apt-get install -y build-essential curl file git
RUN useradd -m -s /bin/bash linuxbrew \
		&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER linuxbrew
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
USER root
ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"

USER vscode

RUN sudo apt-get install -y iverilog gtkwave

CMD ["/bin/bash"]
